events {}

http {

    upstream auth-service {
        server auth-server:3000;
    }

    upstream booking_service {
        server booking-server:3001;
    }

    upstream search_service {
        server search-server:3001;
    }

    server {
        listen 80;

        location /api/users/ {
            proxy_pass http://auth-service/api/users/;
        }

        location /api/bookings {
            proxy_pass http://booking_service/api/bookings;
        }

        location /api/search/hotels {
            proxy_pass http://search_service/api/search/hotels;
        }
    }
}